name: Radar El Peruano
on:
  schedule:
    # 11 AM a 11 PM Perú es 16:00 a 04:00 UTC
    - cron: '*/20 16-23 * * *'
    - cron: '*/20 0-4 * * *'
  workflow_dispatch: 

jobs:
  run_radar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependencias
        run: pip install requests beautifulsoup4 pytz
      - name: Ejecutar Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python radar_peruano.py
      - name: Guardar Memoria
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'action@github.com'
          git add ultima_norma.txt || true
          git commit -m "Actualizar memoria de normas" || exit 0
          git push
